### PR TITLE
Add SaberMod Kernel Toolchains

### PR DESCRIPTION
**Pull request by deadman96385**
Needed for a upcoming change to deathly

### CODE REVIEW

**Comment by DHOMD** [comment]
It's fine with me,.. but care to elaborate on what is missing from CFX's?

**Comment by deadman96385** [comment]
Never used them so i do not know if they work properly, and if they are updated as frequently as these ones. (Friends with Cl3Kener)

**Comment by DHOMD** [comment]
We have used Cfx's for about a year and his tend to be impeccably optimized and updated.  I believe he is the only optimized toolchain with polly plugin.

I'm open to using others if they met the same standards.

**Comment by deadman96385** [comment]
Wow sorry to waste your time meant to open that with validusaosp, instead of vaniraosp. It would not affect you at all because you are not running my d2lte kernel.

**Comment by DHOMD** [comment]
LOL no worries.

If you want to try your kernel over here,.. feel free

**Pull request closed without merging**
