### PR TITLE
d2lte kernel.

### PR DESCRIPTION
**Pull request by animaL-vx**
changed the default kernel for the d2s.

### CODE REVIEW

**Comment by DHOMD** [comment]
IF you move this to gerrit, Im sure people will test.

If I had not already started my nightlies, I would have included it

**Comment by sudosurootdev** [comment]
@DHOMD if it's not a problem, close this up, so we have no open issues here on Github. Thanx Bro! :+1: 

I meant pull requests... the issues are over here: https://github.com/VanirAOSP/device_lge_p880/issues/2 where @nuclearmistake has an open one of. LOL :smiley_cat:

**Comment by nuclearmistake** [comment]
Pull requests have one place: TheMuppets proprietary repos. Gerrit or bust. Chris, you have push access for everything g2. Use it.

**Comment by sudosurootdev** [comment]
Yeah, I just noticed this was open, while browsing VanirAOSP user dashboard... and the g2's... I'm doing it bro. :+1: 

One last thing, can you @nuclearmistake or @DHOMD please switch the ls980 vs980 d800 d801 d802 d803 all to L5 in settings... thanx brothers!!!

**Comment by DHOMD** [comment]
if i knew if this was mainatined I probably would merge it

**Pull request closed without merging**
